# Generated by Django 3.1 on 2020-09-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('ite_id', models.IntegerField()),
            ],
        ),
    ]
